export {
  analyzeBehavioralSamples,
  aggregateSuspicionScore,
  buildBehavioralSignals,
  createBehavioralClientDetector,
  hasCdpInputCoordinateLeak,
  hasCenteredClicks,
  hasClickWithoutMouseMovement,
  hasInstantClickPress,
  hasInterpolatedMouseMovement,
  hasLinearMouseMovement,
  hasLinearTapRhythm,
  hasLinearTouchMovement,
  hasLinearScroll,
  hasLinearTyping,
  hasNoMouseActivity,
  hasSyntheticEvents,
  hasTeleportMouse,
  hasTeleportTouch,
  hasZeroMouseMovementDeltas,
  resolveConfidence,
} from "./behavioral/index.js";
export {
  aggregateInstantSuspicionScore,
  buildInstantSignals,
  checkCdpRuntime,
  checkHighEntropyUserAgentData,
  checkMediaDevices,
  checkNotificationPermissionConsistency,
  checkShaderF16Support,
  checkSpeechVoices,
  checkWorkerConsistency,
  detectInstantClient,
  detectInstantClientAsync,
  isHuman,
  isHumanAsync,
  isBotUserAgent,
  isAutomationArtifacts,
  isCanvasNoiseInjected,
  isCanvasTampered,
  isChromeDriver,
  isChromiumBrowser,
  isDefaultAutomationViewport,
  isEmptyPlugins,
  isEngineInconsistent,
  isErrorStackAutomation,
  isGpuPlatformMismatch,
  isIframeInconsistent,
  isLanguageInconsistent,
  isMediaQueryInconsistent,
  isMissingChromeObject,
  isMissingGreaseBrand,
  isMissingProprietaryCodecs,
  isNativeFunctionTampered,
  isNavigatorIdentityInconsistent,
  isPlaywright,
  isPluginArrayInconsistent,
  isPluginMimeTypeInconsistent,
  isPuppeteer,
  isScreenGeometryInconsistent,
  isSoftwareRenderer,
  isSuspiciousHardware,
  isSuspiciousWebDriverDescriptor,
  isSuspiciousWindowDimensions,
  isTimezoneInconsistent,
  isUserAgentDataMismatch,
  isZeroConnectionRtt,
  resolveInstantConfidence,
} from "./detectInstantClient.js";
export {
  aggregateServerSuspicionScore,
  buildServerSignals,
  createIpListChecker,
  detectServerClient,
  detectServerClientAsync,
  enrichServerContext,
  findTlsFingerprintEntry,
  getDefaultIpDataDir,
  getIpListChecker,
  getTimezoneOffsetMinutes,
  getUserAgentFamily,
  isAcceptLanguageGeoMismatch,
  isBrowserLikeUserAgent,
  isClientHintsMismatch,
  isClientHintsMobileMismatch,
  isClientLanguageMismatch,
  isClientPlatformMismatch,
  isClientUserAgentMismatch,
  isDatacenterBrowserMismatch,
  isKnownSuspiciousTlsFingerprint,
  isMissingTlsFingerprint,
  isMissingBrowserHeaders,
  isScriptingUserAgent,
  isTimezoneMismatch,
  isTlsUserAgentMismatch,
  isValidJa3Hash,
  KNOWN_SUSPICIOUS_TLS_FINGERPRINTS,
  lookupClientIpGeo,
  normalizeTlsFingerprint,
  parseIp,
  preloadIpLists,
  resetIpListCheckerCache,
  resolveServerConfidence,
} from "./server/index.js";
export type {
  AutomationAssessment,
  AutomationConfidence,
  AutomationKind,
} from "./automation.js";
export type { WorkerChecks } from "./asyncChecks.js";
export type {
  BehavioralClientDetector,
  BehavioralClientResult,
  BehavioralDetectorOptions,
  BehavioralSampleCounts,
  BehavioralSamples,
  BehavioralSignal,
  ClickSample,
  ConfidenceLevel,
  KeySample,
  MouseSample,
  ScrollSample,
  TouchSample,
} from "./behavioral/types.js";
export type {
  CrawlerVerificationStatus,
  EnrichedServerContext,
  IpGeoResult,
  IpListChecker,
  IpListMatchResult,
  ParsedIp,
  ServerClientContext,
  ServerClientResult,
  ServerConfidenceLevel,
  ServerDetectorOptions,
  ServerSignal,
  TlsFingerprintEntry,
  UserAgentFamily,
} from "./server/index.js";
export type {
  ExtendedDocument,
  ExtendedNavigator,
  ExtendedWindow,
  InstantAsyncChecks,
  InstantClientAsyncResult,
  InstantClientResult,
  InstantConfidenceLevel,
  InstantDetectorOptions,
  InstantSignal,
  InstantSignalChecks,
} from "./types.js";
export { VERSION } from "./version.js";
